<?php

class ReproTest extends \PHPUnit\Framework\TestCase
{

    use \Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass();
        var_dump("setUpBeforeClass");
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        var_dump("setUp");
    }


    public function test_it_works()
    {
        Mockery::mock(\Floppy012\PhpunitMockeryBug\MockClass::class)
            ->shouldReceive('test')
            ->once();
        $this->assertTrue(true);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        var_dump("tearDown");
    }


    public static function tearDownAfterClass(): void
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
        var_dump("tearDownAfterClass");

    }


}